name: Deploy Final V3

on:
  push:
    branches: [ "deploy" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Ejecutar comandos en AWS
        uses: appleboy/ssh-action@v1.0.3
        with:
          # ESCRIBE TU IP AQUÍ DIRECTAMENTE ENTRE COMILLAS
          host: "3.80.103.181" 
          username: "ec2-user"
          # El secreto de la llave suele fallar menos, mantenlo así:
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            # Usamos sudo por si acaso y rutas directas
            sudo docker rm -f front || true
            sudo docker run -d --name front --network host luisr2004/innovatech-front:latest
