name: Deploy Final V3

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Ejecutar comandos en AWS
        uses: appleboy/ssh-action@v1.0.3
        with:
          # Usamos las comillas para asegurar que lea el texto
          host: "${{ secrets.EC2_HOST }}"
          username: "ec2-user"
          key: "${{ secrets.EC2_SSH_KEY }}"
          port: 22
          script: |
            # Ejecutamos con sudo directo y rutas simples
            sudo docker rm -f front || true
            sudo docker run -d --name front --network host luisr2004/innovatech-front:latest
